language: objective-c

env:
  global:
    #- LATEST_TAG=1
    # PYPI_PASS for deployment
    - secure: "oupMUSNsfPH+jGxLlRfembe6dwdrd85/GlpgIpNxgCURvrsFWZCQDUvgMn+IaBz97Meovb9SrgrADT4dg+86wJ7tAfEEnFTq8nwuFkC8A2fvFHMIKV9PvUx7VLooQWje1u2BbqBk2UwpV9h9lq4QenpJXp/lqIORJg3d7wHcHpY="
  matrix:
    - VERSION=2.7.8 NUMPY=1.7.1
    - VERSION=3.3.5 NUMPY=1.7.1
    - VERSION=3.4.1 NUMPY=1.7.1
    - VERSION=3.5.0 NUMPY=1.9.3

install:
  - cd terryfy && git fetch && git checkout master && cd ..
  - source terryfy/travis_tools.sh
  - travis_retry get_python_environment macpython $VERSION venv
  - if [ -n "$LATEST_TAG" ]; then 
      checkout_closest_tag rawpy ;
    else
      cd rawpy ;
      git fetch ;
      git checkout -f master ;
      git log -n 1 ;
      cd .. ;
    fi
  - cd rawpy
  - travis_retry pip install numpy==$NUMPY
  # scikit-image requires scipy, but doesn't have it as install dependency
  - travis_retry pip install scipy
  # scikit-image requires mpl, however mpl dropped python 3.3 support in mpl 1.5
  - if [[ $VERSION == '3.3.5' ]]; then travis_retry pip install "matplotlib<1.5" ; fi
  - travis_retry pip install -r dev-requirements.txt
  - pip freeze
  - brew rm jpeg
  - brew install --universal jpeg
  - export CC=clang
  - export CXX=clang++
  - export CFLAGS="-arch i386 -arch x86_64"
  - export CXXFLAGS=$CFLAGS
  - export LDFLAGS=$CFLAGS
  - export ARCHFLAGS=$CFLAGS
  - python setup.py bdist_wheel
  - pip install delocate
  - delocate-listdeps --all dist/*.whl # lists library dependencies
  - delocate-wheel --require-archs=intel dist/*.whl # copies library dependencies into wheel
  - delocate-listdeps --all dist/*.whl # verify
  - rename_wheels dist
  - pip install dist/*.whl
  - cd ..

script:
  # make sure it's working without any required libraries installed
  - brew rm jpeg 
  - mkdir tmp_for_test
  - cd tmp_for_test
  - nosetests --verbosity=3 --nocapture ../rawpy/test
  - cd ..

after_success:
  - cd rawpy
  - "if [[ \"`git log -n 1 --pretty=format:'%d'`\" =~ \"tag: v\" ]]; then
       pip install twine ;
       twine upload -u neothemachine -p $PYPI_PASS dist/* ;
     fi"
